on:
#   release:
#     types: [created]
  push:
    branches:
      - master
      - impl


name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "Install dependencies"
        run: |
          npm install -g vsce
          npm i
      - name: "🚀  publish package"
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
